### ISSUE TITLE
Questions about using LX Studio...

### ISSUE THREAD

**Issue by gwertzman** [heronarts/LXStudio#1]
Very excited to see LX Studio posted! Thanks for publishing this project; I'm excited to use it to control a large-scale art project I'm planning for Burning Man.

I have a few basic questions:
1. Is the source code for the LX Studio itself posted anywhere? I see the .jar file, but I'm trying to figure out how the IDE itself works -- there are some mysteries I haven't figured out yet -- but can't find that code anywhere.

2. I'm trying to set up an LED strip connected via Art-Net to test everything out. I have it working, but my strip is GRB color order and the default seems to be RGB so the colors aren't coming out right. I have created a custom strip file, and put it in the "Fixtures" folder, but I'm not seeing it show up in the UI anywhere. Here is my file, and here is what I'm seeing:

```
{
  "label": "Custom strip",

  "strips": [
    {
      "x": 0, "y": 0, "z": 0, "numPoints": 165, "spacing": 10,
      "direction": { "x": 1, "y": 0, "z": 0 }
    },
    {
      "x": 1650, "y": 0, "z": 0, "numPoints": 81, "spacing": 10,
      "direction": { "x": 0, "y": 1, "z": 0 }
    },
    {
      "x": 1650, "y": 810, "z": 0, "numPoints": 165, "spacing": 10,
      "direction": { "x": -1, "y": 0, "z": 0 }
    },
    {
      "x": 0, "y": 810, "z": 0, "numPoints": 81, "spacing": 10,
      "direction": { "x": 0, "y": -1, "z": 0 }
    }
  ],

  "outputs": [
    {
      "protocol": "artnet",
      "host": "192.168.0.60",
      "universe": 0,
      "byteOrder":"grb",
      "start": 0, "num": 170
    },
    {
      "protocol": "artnet",
      "host": "192.168.0.60",
      "universe": 1,
      "byteOrder":"grb",
      "start": 171, "num": 170
    },
    {
      "protocol": "artnet",
      "host": "192.168.0.60",
      "universe": 2,
      "byteOrder":"grb",
      "start": 341, "num": 170
    },
    {
      "protocol": "artnet",
      "host": "192.168.0.60",
      "universe": 3,
      "byteOrder":"grb",
      "start": 511, "num": 170
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/5552690/114836929-003c5880-9d88-11eb-994d-31ecdad22640.png)

Should I be seeing my new fixture in that list? Is there something else I should be doing to add it to my scene?

Thanks for help with these!

**Comment by mcslee** [comment]
Hi James - glad you've found LX Studio. Quick question, are you working with LXStudio-IDE or LXStudio-P3? To load up your custom fixture, you will need to put that in the fixtures folder:
https://github.com/heronarts/LXStudio-P3/tree/master/LXStudio/Fixtures
https://github.com/heronarts/LXStudio-IDE/tree/master/Fixtures

Then you will need to restart LX Studio.

One minor thing on your definition:
>       "start": 171, "num": 170

I think you want start: 170 since these are 0 indexed. If you start at 0 then 171 then 341 you're going to be skipping a pixel. You want, 0 170, 340, 510.

Your outputs also define more pixels than you actually have in your fixture. I see four strips with 165, 81, 165, and 81 points for a total of 492 LED points. So your total number of points in your output packets should not exceed 492.

e.g. perhaps your four universes would be like this
start: 0, num: 165
start: 165, num: 81
start: 246, num: 165
start: 411, num: 81

The source code for the LX Studio application is not open source. The lower level libraries are provided for reference but all the UI of the application itself is closed source. Happy to answer questions if you have them and javadocs are available here:
http://lx.studio/api/

Hope this helps with the fixture definitions, let me know how it goes!

**Comment by gwertzman** [comment]
Thanks! Turns out it was a path issue! 

By putting "Fixtures" in the "lib" folder, I got it to read the file correctly -- so my custom fixture now shows up in the list of available fixtures correctly, and now everything is working!

Next question... are there any docs or videos anywhere on actually using LX Studio? Through trial and error I'm figuring out the basics, like connecting modulators to parameters in the UI, but there still so many mysteries. Like what does the "ld" button on each fixture do? etc.

**Comment by mcslee** [comment]
Ah yes - for some reason on Windows machines it seems to want the "lib"
folder to be where files are. Haven't dug into exactly why the
mismatch there, but throwing your assets in lib/ should solve the problem.

Sadly documentation is admittedly a bit lacking. You will have to play
catch-up a bit on that. "Id" identifies a fixture, it will turn all other
fixtures dark and the selected fixture will pulse red.

Note that a decent # of things are self-documenting via the help bar on the
bottom:

[image: Screen Shot 2021-04-15 at 1.12.30 PM.png]

**Comment by mcslee** [comment]
<img width="1631" alt="Screen Shot 2021-04-15 at 1 12 30 PM" src="https://user-images.githubusercontent.com/597850/114932627-91ddb180-9dec-11eb-8177-a9f3e7ae70bf.png">
