### ISSUE TITLE
Exception while instantiating patterns using LX engine (not LXStudio).

### ISSUE THREAD

**Issue by lexszero** [heronarts/LXStudio#11]
I have a project built upon LX Studio and I run into some strange problem when running headless engine.
I use LXStudio UI for development and preview, and I plan to run my light installation using a headless engine. Everything works awesome when the model is being run using LX Studio with UI, however I get the following errors when using just plain LX engine:

```
Exception in instantiateComponent: LXStudio$EmpathyTreeGradient.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$EmpathyTreeGradient.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$LoopIteratorPattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$SpiralPattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$SpiralPattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$NeoTriangleGradient.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$AllStripePattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$AllStripePattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$AllStripePattern.<init>(heronarts.lx.LX)
Exception in instantiateComponent: LXStudio$AllStripePattern.<init>(heronarts.lx.LX)
```

Obviously, these patterns doesn't work, and what I see is the default GradientPattern and (which I actually use in one place in my project) and IteratorPattern (which I don't use, but I guess it is used as a fallback).

These classes are custom patterns I defined, their source could be found e.g. [here](https://github.com/lexszero/LXStudio/blob/EmpathyTree/LXStudio/EmpathyTreePatterns.pde), (it uses some helper classes such as [NeoPattern](https://github.com/lexszero/LXStudio/blob/EmpathyTree/LXStudio/Patterns.pde#L44) and [NeoModel](https://github.com/lexszero/LXStudio/blob/EmpathyTree/LXStudio/Model.pde#L79), though not much magic happen there). Initialization of LX object happens [here](https://github.com/lexszero/LXStudio/blob/EmpathyTree/LXStudio/LXStudio.pde#L40-L48).

Those error messages are not very informative and I don't know how to proceed. I've also looked into the source code of LX engine where this exceptions are coming from, but that didn't explained much.
Am I doing something wrong (I'm pretty bad in Java) or is it actually a bug?

Maybe this issue actually belongs to the LX engine repository.

Thank you for your time and for making a great software!

**Comment by mcslee** [comment]
Hi Alex - so the issue here is that your pattern classes are part of your Processing project and are not declared static. This means that when they are constructed dynamically, they actually have a first parameter of the Processing sketch. You can take a look at how the P3LX source code dynamically loads these here: https://github.com/heronarts/P3LX/blob/master/src/heronarts/p3lx/P3LX.java#L251

Now, when you declare your headless version using LX instead of P3LX/LXStudio, it's going to use the raw LX version of the component instantiation code: https://github.com/heronarts/LX/blob/master/src/heronarts/lx/LX.java#L992

This version of the code doesn't know to look for constructors that are inner classes of a Processing sketch.

The simplest fix would be for you to declare all your pattern/effect classes to be static, e.g.:
```
public abstract static class NeoPattern extends LXModelPattern<Model> {
public static abstract class EmpathyTreePattern extends NeoPattern {
```

etc.

Let me know if that works for you!

This project looks very cool by the way. Just curious, where you are from? How'd you find out about LX Studio? Is this tree going to be built and shown somewhere?

**Comment by mcslee** [comment]
BTW I will also add better debugging in a future release of the LX engine so that a proper full stack trace gets dumped for these instantiation errors.

**Comment by lexszero** [comment]
This actually helped a lot. Haven't tested with the hardware yet, but at least I don't get any exceptions with static. Thanks for a quick answer!

I live in Finland, and the tree is an installation for a local Decompression event on the next weekend. I've heard of LX Studio on The Borderland (northern Europe regional Burning Man event), from a guy who has  built a light installation there.

**Comment by mcslee** [comment]
Great - glad to hear that solved the issue. Will close out this task for now, but feel free to re-open if other questions around this behavior come up.

Would love to see some photo/video of your final install when it comes out! Always nice to see people using the software, sounds like there have been a few projects I didn't even realize occurred!
