### ISSUE TITLE
only the first pattern declared in lx.setPatterns is selectable when run

### ISSUE THREAD

**Issue by rowr111** [heronarts/LXStudio#14]
I listed three patterns in lx.setPatterns in setup but only the first one listed is selectable in Channel-1, even though they all appear there.  If I try double-clicking on patterns from the list in Browser, they appear (multiple times even) in the channel-1 window but are not selectable.  If I change the order in setPatterns, I am able to run other patterns, but the same problem exists (no other patterns are selectable).

**Comment by mcslee** [comment]
Hrm, can you explain precisely what happens when you try to select a pattern in the Channel-1 box? To activate a pattern there, you need to either double-click on it or press return when it is selected.

What is happening when you attempt to do that? If you can add a screenshot or video-capture of what happens when you try to select, or explain exactly what you're clicking/pressing and then what is happening (or not happening) - will try to figure this out.

**Comment by rowr111** [comment]
Thanks for the response - I included a video that shows that the patterns are listed but not selectable.  If I try to click on or navigate via the arrow keys to other patterns, it doesn't seem to recognize that there are other patterns there and I cannot get focus to go onto any pattern other than the first one.

[LXStudio 2019-01-14 10_52_32 AM.zip](https://github.com/heronarts/LXStudio/files/2753841/LXStudio.2019-01-14.10_52_32.AM.zip)

**Comment by mcslee** [comment]
Ah, how weird. Tested this out on my system and I'm able to reproduce when the setPatterns() call is in the setup() method rather than the initialize() callback.

I'm guessing that your call to setPatterns() is inside the Processing setup() method?

Instead of that, try putting the setPatterns() call inside the initialize() callback. This is a top-level function in your Processing sketch, and generally speaking it is better to put your initialization code inside here, as opposed to directly in the setup() call.

e.g.
```
void initialize(final heronarts.lx.studio.LXStudio lx, heronarts.lx.studio.LXStudio.UI ui) {
  // Add custom components or output drivers here
  lx.setPatterns(new LXPattern[] {
    new GradientPattern(lx),
    new GradientPattern(lx),
    new GradientPattern(lx)
  });
}
```

I believe this will fix your issue (it does on my system). That said, I'm still going to consider this a bug and will look into why it's behaving strangely when done the other way. Seems like the UI list object is not updating its size properly (which is why that click is going to item 0 in the list even when there's clearly more items).

Let me know if moving the initialization fixes your issue in the meantime. Thanks for the video-grab, super helpful to understand what was going on. Cheers!

**Comment by rowr111** [comment]
That fixed my issue, thanks so much!  And thank you for such prompt help! :D

**Comment by mcslee** [comment]
FYI - this should be fixed by: https://github.com/heronarts/LX/commit/a8d897583763d062edfc4396e93b2b1c62208de6

This will eventually make its way into the standard LXStudio build. I still recommend making this call from within initialize().
