### ISSUE TITLE
NoSuchMethodException with P3LXPatterns

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#6]
In `heronarts.lx.studio.ui.browser.UIPatternManager$PatternItem.onActivate`, it looks like `P3LXPattern`s are instantiated with `(PApplet,LX)`, when the constructor is actually `(P3LX)`.

All classes having a `P3LXPattern` parent can't load.

**Comment by mcslee** [comment]
Hey Shawn - I actually just earlier changed P3LXPattern so that its constructor signature is consistent with what the auto-loader looks for: https://github.com/heronarts/P3LX/commit/4154709bf4d80adac00833b57f979a6eba46bb25

I will get that release and versioning stuff fixed up this afternoon so you guys can integrate this and the other relevant recent changes.
