### ISSUE TITLE
Loading the example json from "Custom JSON Fixtures" documentation results in errors.

### ISSUE THREAD

**Issue by oveddan** [heronarts/LXStudio#8]
I'm attempting to follow the [Custom JSON Fixtures tutorial](https://github.com/heronarts/LXStudio/wiki/Custom-JSON-Fixtures).  When Ioad that example json into lxstudio, the following errors show up:

<img width="184" alt="Screenshot 2023-06-30 at 5 45 20 PM" src="https://github.com/heronarts/LXStudio/assets/891755/317fe551-053b-44f9-ab1a-4ea1da4868ce">

Would it be possible to update that example with the correct schema for the current version of LXStudio?

**Comment by mcslee** [comment]
Sorry about that - this wasn't ever intended to be copy/pasted or create something sensible, vs. indicating the syntax. But good idea to not have glaring errors in it.

Updated now.

The ChildJSON.lxf error will still appear, since there's no sub-file to be bundled here - but I believe the other warnings should be cleaned up. Thx for flagging this.
