### ISSUE TITLE
P3LX JARs differ between the same version of LXStudio release and P3LX release

### ISSUE THREAD

**Issue by ssilverman** [heronarts/LXStudio#9]
These JARs are different. Which one is actually 0.1.0-alpha?
I'll add: Is the P3LX JAR from the P3LX GitHub project compatible with the LXStudio.jar build from the LXStudio GitHub project?

**Comment by mcslee** [comment]
Apologies - that is really weird, I can't figure out why that happened. The difference seems to just be the presence of "lxstudio.png" at the top-level. I don't know why it's there. Very strange.

I do need to clean up some build scripts, as the one in P3LX does a bunch of Processing library packaging stuff that my more lightweight LXStudio build script doesn't do. Will get this sorted out shortly.

Regardless - yes, the P3LX JAR from GitHub should be project compatible with LXStudio.jar in the LXStudio project.

**Comment by ssilverman** [comment]
In my opinion, JARs that are labeled with the same version should be binary-identical. I used `diff`.

**Comment by ssilverman** [comment]
A note on build scripts. I've been liking Maven; it does all the things I need and I suspect it could assist you. Feel free to reach out if you'd like Maven assistance.

**Comment by mcslee** [comment]
> In my opinion, JARs that are labeled with the same version should be binary-identical. I used diff.

Totally agree in principle and I've just been trying to sort all of this out. However, because a JAR is a ZIP file, and ZIP files include timestamps, it turns out that re-building the same exact release from the same sources will not diff exactly... the resulting JAR file will depend upon when the .class files were compiled.

I've been using "unzip -l" to compare, or "diff -ur" with the unzipped folders to ensure contents are identical.

I suppose as a matter of release process I can try to ensure that the version of P3LX.jar in the P3LX repo is the "canonical" version - but I just wanted to point this out for context, as when I rebuild things for my full LXStudio packaging, the timestamps are going to be different.

Looking at Maven has been on my TODO list, maybe post-Burn. LMK if you have a good quick primer on it... quite a lot of info to sift thru on the main site.

**Comment by ssilverman** [comment]
Post-Burn would be great. Where are you camped? :)

**Comment by mcslee** [comment]
Short Stack! We'll be at 4:30/C. Drop by anytime - we have a big Tutu Tuesday party all afternoon on Tues.

FYI - just cut 0.1.1 releases on all the repositories, the JARs ought to be consistent now, and they all contain a VERSION file within them.

Also there's now LX.VERSION, P3LX.VERSION and LXStudio.VERSION identifiers (all the same) if you want to check from code.
